version: '3'
services:
  database:
    container_name: database-ise
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data
  redis:
    container_name: redis-ise
    image: redis:latest
    restart: always
    environment:
      CACHE_PASS: ${CACHE_PASS}
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${CACHE_PASS}
    ports:
      - ${CACHE_PORT}:6379
    expose:
      - ${CACHE_PORT}
    volumes:
      - ./docker/cache/data:/var/lib/redis/data
      - ./docker/cache/config:/usr/local/etc/redis/redis.conf

volumes:
  mysqldata:
  redis:
