---
version: '3'
services:
  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./docker/volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
