name: Deploy Backend Development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Logged and Run Deploy
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          #   password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nuii/nuii-dev
            git stash
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git stash apply
            npm install
            npm run build
            pm2 restart nuii-dev

      - name: Notify Success
        if: success()
        run: echo "🚀 Deployment was successful"
